---

- name: starting playbook
  hosts: nginx
  become: yes
  
  roles:
    - nginx
    - mysql
    - wordpress









  # handlers:
  
  #   - name: restart nginx
  #     service: name=nginx state=restarted
  #   - name: enable nginx
  #     service: name=nginx state=started enabled=yes
  #   - name: Set the root password
  #     mysql_user:
  #       name: root
  #       password: "{{ mysql_root_password }}"
  #       login_unix_socket: /var/run/mysqld/mysqld.sock
  #     tags: [ mysql, mysql-root ]
