---
# tasks file for nginx

---
# defaults file for nginx


    - name: install nginx
      apt: name=nginx state=present update-cache=yes
     # notify: enable nginx
#    - name: enable nginx
#      service: name=nginx state=started enabled=yes

    - name: install php
      apt: name=php,php-cli,php-fpm,php-mysql,php-json,php-opcache,php-mbstring,php-xml,php-gd,php-curl state=present update-cache=yes
    
    - name: enable php
      service: name=php8.1-fpm state=started enabled=yes

    - name: remove defaults
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx/sites-available/default
        - /etc/nginx/sites-enabled/default
     # notify: restart nginx
